### ISSUE TITLE
Issues and Tickets Page

### ISSUE THREAD

**Issue by afrze** [afrze/flyers-desk#32]
- Once Issues are created, get issues based on the UID logged in and get the issues and populate the page.
- Get all the issues created and populate the tickets page. 
- Set priority on the tickets
- Add Assigned To value on the Ticket
- Add filters in tickets to based on
  - Status
  - Assigned To
  - Priority

**Comment by manoj-surabathulla** [comment]
- created open ticket by using params 
- created assigne_id, status for the infra team
- fixed date stamp to be displayed in UI
- created active link color
